org.store:
  Location: Hanoi
  Tags:
    - Iphone
    - Ipad
  NumberProducts: 1
  products:
    - title: Iphone 6
      price: 600
      currency: $
      variants:
        - color: red
          storage: 64gb
          images:
            Sm:
              size: 120
              width: 120
              height: 80
            Xl:
              size: 800
              width: 800
              height: 600
