org:
  store:
    open: false
    Location: Hanoi
    Tags:
      - Iphone
      - Ipad
    NumberProducts: 1
    products:
      - title: Iphone 6
        price: 600
        variants:
          - color: red
            storage: 64gb
            images:
              Normal:
                size: ""
                width: 120
                height: 80
              Thumb:
                size: "thumb"
                width: 80
                height: 80
                isDefault: false
