org:
  store:
    Location: Hanoi
    Tags:
      - Iphone
      - Ipad
    NumberProducts: 2
    products:
      - title: Iphone 6
        price: 600
        currency: $
        variants:
          - color: red
            storage: 64gb
          - color: blue
            storage: 128gb
      - title: Iphone 13 Pro
        price: 45000000
        currency: VND
        variants:
          - storage: 1TB
            color: yellow
